"""Add extened interace field

Revision ID: 98f66c9ea66b
Revises: 
Create Date: 2025-12-29 09:16:19.368939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98f66c9ea66b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interfaces', sa.Column('type', sa.String(), nullable=True))
    op.add_column('interfaces', sa.Column('line_protocol', sa.String(), nullable=True))
    op.add_column('interfaces', sa.Column('mac_address', sa.String(), nullable=True))
    op.add_column('interfaces', sa.Column('mtu', sa.Integer(), nullable=True))
    op.add_column('interfaces', sa.Column('speed', sa.String(), nullable=True))
    op.add_column('interfaces', sa.Column('duplex', sa.String(), nullable=True))
    op.add_column('interfaces', sa.Column('link_type', sa.String(), nullable=True))
    op.add_column('interfaces', sa.Column('media_type', sa.String(), nullable=True))
    op.add_column('interfaces', sa.Column('auto_negotiate', sa.String(), nullable=True))
    op.add_column('interfaces', sa.Column('ip_address', sa.String(), nullable=True))
    op.add_column('interfaces', sa.Column('subnet_mask', sa.String(), nullable=True))
    op.add_column('modules', sa.Column('name', sa.String(), nullable=False))
    op.add_column('modules', sa.Column('hw_revision', sa.String(), nullable=True))
    op.add_column('modules', sa.Column('under_warranty', sa.Boolean(), nullable=True))
    op.drop_column('modules', 'warranty_from')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('warranty_from', sa.DATE(), nullable=True))
    op.drop_column('modules', 'under_warranty')
    op.drop_column('modules', 'hw_revision')
    op.drop_column('modules', 'name')
    op.drop_column('interfaces', 'subnet_mask')
    op.drop_column('interfaces', 'ip_address')
    op.drop_column('interfaces', 'auto_negotiate')
    op.drop_column('interfaces', 'media_type')
    op.drop_column('interfaces', 'link_type')
    op.drop_column('interfaces', 'duplex')
    op.drop_column('interfaces', 'speed')
    op.drop_column('interfaces', 'mtu')
    op.drop_column('interfaces', 'mac_address')
    op.drop_column('interfaces', 'line_protocol')
    op.drop_column('interfaces', 'type')
    # ### end Alembic commands ###
