"""Initial schema with interfaces fields

Revision ID: fa350ff4b44b
Revises: 98f66c9ea66b
Create Date: 2025-12-29 09:25:21.522728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa350ff4b44b'
down_revision: Union[str, Sequence[str], None] = '98f66c9ea66b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('mgmt_address', sa.String(), nullable=False),
    sa.Column('vrf', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('device_group', sa.String(), nullable=True),
    sa.Column('uptime', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname')
    )
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_table('software_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('os_version', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('vulnerability', sa.Text(), nullable=True),
    sa.Column('last_scanned', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('os_version')
    )
    op.create_index(op.f('ix_software_versions_id'), 'software_versions', ['id'], unique=False)
    op.create_table('mac_address_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('vrf', sa.String(), nullable=True),
    sa.Column('mac_address', sa.String(), nullable=False),
    sa.Column('interface_name', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mac_address_table_id'), 'mac_address_table', ['id'], unique=False)
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('part_number', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('hw_revision', sa.String(), nullable=True),
    sa.Column('under_warranty', sa.Boolean(), nullable=True),
    sa.Column('warranty_expiry', sa.Date(), nullable=True),
    sa.Column('environment_status', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_id'), 'modules', ['id'], unique=False)
    op.create_table('routing_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('vrf', sa.String(), nullable=True),
    sa.Column('route', sa.String(), nullable=False),
    sa.Column('next_hop', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routing_table_id'), 'routing_table', ['id'], unique=False)
    op.create_table('running_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_running_config_id'), 'running_config', ['id'], unique=False)
    op.create_table('software_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('firmware_version', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['software_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_software_info_id'), 'software_info', ['id'], unique=False)
    op.create_table('vlans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('vlan_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('membership', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vlans_id'), 'vlans', ['id'], unique=False)
    op.create_table('interfaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('line_protocol', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('mtu', sa.Integer(), nullable=True),
    sa.Column('speed', sa.String(), nullable=True),
    sa.Column('duplex', sa.String(), nullable=True),
    sa.Column('link_type', sa.String(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('auto_negotiate', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('subnet_mask', sa.String(), nullable=True),
    sa.Column('vrf', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('sfp_module_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sfp_module_id'], ['modules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interfaces_id'), 'interfaces', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interfaces_id'), table_name='interfaces')
    op.drop_table('interfaces')
    op.drop_index(op.f('ix_vlans_id'), table_name='vlans')
    op.drop_table('vlans')
    op.drop_index(op.f('ix_software_info_id'), table_name='software_info')
    op.drop_table('software_info')
    op.drop_index(op.f('ix_running_config_id'), table_name='running_config')
    op.drop_table('running_config')
    op.drop_index(op.f('ix_routing_table_id'), table_name='routing_table')
    op.drop_table('routing_table')
    op.drop_index(op.f('ix_modules_id'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_mac_address_table_id'), table_name='mac_address_table')
    op.drop_table('mac_address_table')
    op.drop_index(op.f('ix_software_versions_id'), table_name='software_versions')
    op.drop_table('software_versions')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
